### PR TITLE
Allow service to update token

### PR DESCRIPTION
**Pull request by brennon**
I have a need to set the input token with a value received from an API call. Injecting $http into LogglyLoggerProvider's config() isn't possible, and updating the token through the service wasn't possible, either (or, I wasn't able to figure out how to do so.) This commit exposes an inputToken() method on the service that allows the consumer to update the token after configuration.

### CODE REVIEW

**Comment by ajbrown** [comment]
@brennon One more update -- please resolve the merge conflicts.

**Comment by brennon** [comment]
Should be all set. Conflict was in the minified script—only solution was to revert to the minified script and map that *do not* include other changes in the pull request.

**Comment by ajbrown** [comment]
Thanks @brennon !

**Comment by brennon** [comment]
My pleasure, @ajbrown.

**Pull request merged**
