### PR TITLE
Using http

### PR DESCRIPTION
**Pull request by psquickitjayant**
1. Removed Image src request to send events to Loggly
2. Added `$http.post` to send requests to Loggly

### CODE REVIEW

**Comment by ajbrown** [comment]
@psquickitjayant The img.src was originally used to get around CORS issues (if I recall correctly).  Is this now working correctly with the `$http.post` request?

**Comment by ajbrown** [comment]
It looks like you're removing a lot of the tests.  If the `$http.post` does in fact work, we'll want to update the tests as well.

**Comment by psquickitjayant** [comment]
@ajbrown  yes, Loggly has deployed CORS header on their servers. We will be adding test cases soon, you can also help in doing that.

**Comment by psquickitjayant** [comment]
@ajbrown  We have updates test cases. Please review.

**Comment by psquickitjayant** [comment]
@ajbrown please check if this PR can be merged. We have added all the required test cases.

**Comment by ajbrown** [comment]
@psquickitjayant Thanks! I'll go ahead and cut this into a new release now as well.

**Comment by ajbrown** [comment]
@psquickitjayant Sorry false alarm.  I just noticed this is targetting `master`.  Can you re-open targetting `develop`?

**Comment by psquickitjayant** [comment]
sure, thanks!

**Comment by psquickitjayant** [comment]
I can see new merges after the code update. I will rebase the code and update it and submit the new pull request.

**Pull request closed without merging**
