### PR TITLE
Added support to custom JSON logging

### PR DESCRIPTION
**Pull request by psquickitjayant**
1. Added support to custom JSON
2. Added support to tags
3. Added support to configure console errors
4. Bug fixes

Hey @ajbrown 
Reverted all the modifications, then pulled your changes and my changes.

### CODE REVIEW

**Comment by ajbrown** [comment]
@psquickitjayant looks like the tests are failing.  Can you take a look?

**Comment by psquickitjayant** [comment]
@ajbrown  Seems all worked well.

**Comment by psquickitjayant** [comment]
@ajbrown  We can also add test cases for the plain text, custom JSON and console errors as I have added checks for each of these. Also we can make a separate test case for the identifier "sendConsoleErrors". You can know more about sendConsoleErrors by looking into the ReadMe file.

**Comment by ajbrown** [comment]
Thanks for this!

**Pull request merged**
